Friend Module Constants
    Friend Const AbandonGameText = "Abandon Game"
    Friend Const CharacterNamePrompt = "[olive]Character Name:[/]"
    Friend Const CharacterNameDefault = "Tagon"
    Friend Const ConfirmAbandonGameTitle = "[red]Are you sure you want to abandon the game?[/]"
    Friend Const ConfirmQuitTitle = "[red]Are you sure you want to quit?[/]"
    Friend Const GameMenuTitle = "[olive]Game Menu:[/]"
    Friend Const GameMenuText = "Game Menu"
    Friend Const GameTitle = "Blight of SPLORR!!"
    Friend Const MainMenuTitle = "[olive]Main Menu[/]"
    Friend Const NeverMindText = "Never Mind"
    Friend Const NoText = "No"
    Friend Const NowWhatTitle = "[olive]Now What?[/]"
    Friend Const OkText = "Ok"
    Friend Const QuitText = "Quit"
    Friend Const StartGameText = "Start Game"
    Friend Const YesText = "Yes"
End Module
